// SPDX-License-Identifier: GPL-3.0-only
#ifndef PARAMETER_H
#define PARAMETER_H
/* Saved IDs, independent of UI addresses. The device range is reserved for future built-in processors. */
enum { PARAM_CHANNEL_VOLUME=1, PARAM_CHANNEL_PAN, PARAM_CHANNEL_PITCH, PARAM_INSERT_VOLUME, PARAM_INSERT_PAN, PARAM_INSERT_WIDTH, PARAM_MASTER_VOLUME, PARAM_MASTER_WIDTH, PARAM_MASTER_PITCH, PARAM_CHANNEL_MUTE, PARAM_INSERT_MUTE, PARAM_MASTER_MUTE, PARAM_SWING, PARAM_PITCH_RANGE, PARAM_PLUGIN=1024, PARAM_CHORUS_RATE=1025, PARAM_CHORUS_DEPTH, PARAM_EFFECT_MIX, PARAM_FM_RATIO=1101, PARAM_FM_DEPTH, PARAM_FM_ATTACK, PARAM_FM_DECAY, PARAM_FM_SUSTAIN, PARAM_FM_RELEASE, PARAM_FM_MOD_DECAY, PARAM_FM_MOD_SUSTAIN, PARAM_FM_VELOCITY, PARAM_FM_LFO_RATE, PARAM_FM_VIBRATO, PARAM_FM_TREMOLO, PARAM_FM_CARRIER_RATIO, PARAM_FM_CARRIER_DETUNE, PARAM_FM_BODY_DETUNE, PARAM_FM_MOD_ATTACK, PARAM_FM_MOD_RELEASE, PARAM_FM_ATTACK_RATIO, PARAM_FM_ATTACK_DETUNE, PARAM_FM_ATTACK_DEPTH, PARAM_FM_ATTACK_ATTACK, PARAM_FM_ATTACK_DECAY, PARAM_FM_ATTACK_SUSTAIN, PARAM_FM_ATTACK_RELEASE, PARAM_FM_ROUTING, PARAM_FM_LFO_SHAPE, PARAM_FM_LFO_FADE, PARAM_FM_BODY_PITCH, PARAM_FM_LAST=PARAM_FM_BODY_PITCH, PARAM_EQ_FIRST=1201, PARAM_EQ_LAST=1221 };
typedef struct { unsigned parameter,owner,slot; } ParameterTarget;
/* Common control metadata; independent of project layout and UI addresses. */
enum { PARAMETER_CONTINUOUS, PARAMETER_INTEGER, PARAMETER_TOGGLE, PARAMETER_LOGARITHMIC };
typedef struct {
    unsigned id;
    const char *name;
    float low,high,initial;
    int kind;
} ParameterDescriptor;
const ParameterDescriptor *parameter_descriptor(unsigned id);
#endif
