// SPDX-License-Identifier: GPL-3.0-only
#ifndef PROJECT_FORMAT_H
#define PROJECT_FORMAT_H
#define PROJECT_FORMAT_MAGIC "LIBRELOOP_PROJECT"
#define PROJECT_FORMAT_VERSION 1
#define PROJECT_FILE_EXTENSION "llp"
#define PROJECT_FILE_SUFFIX "." PROJECT_FILE_EXTENSION
#endif
