// SPDX-License-Identifier: GPL-3.0-only
#include "ui_internal.h"

UiState ui={
    .record_mask=RECORD_AUDIO,
    .typing_keys=1,
    .output_volume=1,
    .input_enabled=1,
    .picker_drag=-1,
    .automation_selected=-1,
    .automation_node=-1,
    .automation_lane=-1,
    .automation_clip=-1,
    .rename_automation=-1,
    .arrangement={.source_steps=STEPS,.source_pattern=-1,.zoom=1},
    .track_zoom=1,
    .row_zoom_drag=-1,
    .selected_track=-1,
    .track_resize=-1,
    .marker_drag=-1,
    .ruler_last_id=-1,
    .ruler_last_click=-1,
    .rack_filters={"All","Audio","Unsorted"},
    .route_drag=-1,
    .mixer_selected=1,
    .cable_drag=-1,
    .browser_progress=-1,
    .browser_focus=1,
    .browser_width=174,
    .last_sidebar=174,
    .piano_top=72,
    .piano_zoom=1,
    .piano_key=-1,
    .piano_note_length=2,
    .piano_span={16,16,16,16,16,16,16,16},
    .velocity_drag=-1,
    .rack_paint=-1,
    .rack_paint_channel=-1,
    .navigation_drag=-1,
    .eq_drag=-1,
    .fm_graph_drag=-1,
    .status="Use the toolbar to open editors; drag their title bars to arrange them",
    .document={.path="project" PROJECT_FILE_SUFFIX},
    .relink_channel=-1,
    .file_last_row=-1,
    .file_last_click=-1,
    .knob_context=-1,
    .rename_track=-1,
    .rename_mixer=-1,
    .rename_channel=-1,
    .fm_envelope_ids={
    {PARAM_FM_ATTACK,PARAM_FM_DECAY,PARAM_FM_SUSTAIN,PARAM_FM_RELEASE},
    {PARAM_FM_MOD_ATTACK,PARAM_FM_MOD_DECAY,PARAM_FM_MOD_SUSTAIN,PARAM_FM_MOD_RELEASE},
    {PARAM_FM_ATTACK_ATTACK,PARAM_FM_ATTACK_DECAY,PARAM_FM_ATTACK_SUSTAIN,PARAM_FM_ATTACK_RELEASE}
},
};
